<?php
/**
 * This file is part of the ProductReview plugin.
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\ProductReview\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductReview Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductReviewConfigRepository extends EntityRepository
{
}
