parameters:
    eccube.twig.block.templates:
        - 'ProductReview/Resource/template/default/hello.twig'
    plugin_product_review.constant:
        min: 1
        max: 30

services:
    Plugin\ProductReview\Form\:
        resource: '%kernel.project_dir%/app/Plugin/ProductReview/Form'
        bind:
            $productReviewConstant: %plugin_product_review.constant%
        tags: ['form.type']
